name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed  # PR이 닫히거나 머지될 때 실행

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch if merged
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}